// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delay_records.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getTrainStats = `-- name: GetTrainStats :one
SELECT
    train_number,
    COUNT(*) as total_trips,
    SUM(CASE WHEN delay <= 5 AND cancelled = FALSE THEN 1 ELSE 0 END) as on_time_trips,
    SUM(CASE WHEN delay > 5 AND cancelled = FALSE THEN 1 ELSE 0 END) as delayed_trips,
    SUM(CASE WHEN cancelled = TRUE THEN 1 ELSE 0 END) as cancelled_trips,
    AVG(CASE WHEN cancelled = FALSE THEN delay ELSE NULL END) as average_delay,
    MAX(CASE WHEN cancelled = FALSE THEN delay ELSE NULL END) as max_delay
FROM delay_records
WHERE train_number = ?
GROUP BY train_number
`

type GetTrainStatsRow struct {
	TrainNumber    string          `json:"train_number"`
	TotalTrips     int64           `json:"total_trips"`
	OnTimeTrips    sql.NullFloat64 `json:"on_time_trips"`
	DelayedTrips   sql.NullFloat64 `json:"delayed_trips"`
	CancelledTrips sql.NullFloat64 `json:"cancelled_trips"`
	AverageDelay   sql.NullFloat64 `json:"average_delay"`
	MaxDelay       interface{}     `json:"max_delay"`
}

func (q *Queries) GetTrainStats(ctx context.Context, trainNumber string) (GetTrainStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getTrainStats, trainNumber)
	var i GetTrainStatsRow
	err := row.Scan(
		&i.TrainNumber,
		&i.TotalTrips,
		&i.OnTimeTrips,
		&i.DelayedTrips,
		&i.CancelledTrips,
		&i.AverageDelay,
		&i.MaxDelay,
	)
	return i, err
}

const insertDelayRecord = `-- name: InsertDelayRecord :exec
INSERT INTO delay_records (train_number, train_category, origin, destination, date, delay, cancelled, source)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(train_number, date, source) DO UPDATE SET
    delay = excluded.delay,
    cancelled = excluded.cancelled,
    recorded_at = CURRENT_TIMESTAMP
`

type InsertDelayRecordParams struct {
	TrainNumber   string         `json:"train_number"`
	TrainCategory sql.NullString `json:"train_category"`
	Origin        string         `json:"origin"`
	Destination   string         `json:"destination"`
	Date          time.Time      `json:"date"`
	Delay         int64          `json:"delay"`
	Cancelled     sql.NullBool   `json:"cancelled"`
	Source        sql.NullString `json:"source"`
}

func (q *Queries) InsertDelayRecord(ctx context.Context, arg InsertDelayRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertDelayRecord,
		arg.TrainNumber,
		arg.TrainCategory,
		arg.Origin,
		arg.Destination,
		arg.Date,
		arg.Delay,
		arg.Cancelled,
		arg.Source,
	)
	return err
}
