// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import_metadata.sql

package sqlc

import (
	"context"
	"time"
)

const getImportMetadata = `-- name: GetImportMetadata :one
SELECT entity_type, last_import, record_count, import_duration_ms, status, error_message
FROM import_metadata WHERE entity_type = ?
`

func (q *Queries) GetImportMetadata(ctx context.Context, entityType string) (ImportMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getImportMetadata, entityType)
	var i ImportMetadatum
	err := row.Scan(
		&i.EntityType,
		&i.LastImport,
		&i.RecordCount,
		&i.ImportDurationMs,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const upsertImportMetadata = `-- name: UpsertImportMetadata :exec
INSERT INTO import_metadata (entity_type, last_import, record_count, import_duration_ms, status, error_message)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(entity_type) DO UPDATE SET
    last_import = excluded.last_import,
    record_count = excluded.record_count,
    import_duration_ms = excluded.import_duration_ms,
    status = excluded.status,
    error_message = excluded.error_message
`

type UpsertImportMetadataParams struct {
	EntityType       string    `json:"entity_type"`
	LastImport       time.Time `json:"last_import"`
	RecordCount      *int64    `json:"record_count"`
	ImportDurationMs *int64    `json:"import_duration_ms"`
	Status           *string   `json:"status"`
	ErrorMessage     *string   `json:"error_message"`
}

func (q *Queries) UpsertImportMetadata(ctx context.Context, arg UpsertImportMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertImportMetadata,
		arg.EntityType,
		arg.LastImport,
		arg.RecordCount,
		arg.ImportDurationMs,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}
