// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journey.sql

package sqlc

import (
	"context"
	"time"
)

const createJourney = `-- name: CreateJourney :exec
INSERT INTO journey (id, train_number, origin_id, origin_name, destination_id, destination_name,
    scheduled_departure, actual_departure, delay, recorded_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateJourneyParams struct {
	ID                 string     `json:"id"`
	TrainNumber        int64      `json:"train_number"`
	OriginID           string     `json:"origin_id"`
	OriginName         string     `json:"origin_name"`
	DestinationID      string     `json:"destination_id"`
	DestinationName    string     `json:"destination_name"`
	ScheduledDeparture *time.Time `json:"scheduled_departure"`
	ActualDeparture    *time.Time `json:"actual_departure"`
	Delay              *int64     `json:"delay"`
	RecordedAt         time.Time  `json:"recorded_at"`
}

func (q *Queries) CreateJourney(ctx context.Context, arg CreateJourneyParams) error {
	_, err := q.db.ExecContext(ctx, createJourney,
		arg.ID,
		arg.TrainNumber,
		arg.OriginID,
		arg.OriginName,
		arg.DestinationID,
		arg.DestinationName,
		arg.ScheduledDeparture,
		arg.ActualDeparture,
		arg.Delay,
		arg.RecordedAt,
	)
	return err
}

const createJourneyStop = `-- name: CreateJourneyStop :exec
INSERT INTO journey_stop (id, journey_id, station_id, station_name, scheduled_arrival,
    scheduled_departure, actual_arrival, actual_departure, arrival_delay, departure_delay, platform)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateJourneyStopParams struct {
	ID                 string     `json:"id"`
	JourneyID          string     `json:"journey_id"`
	StationID          string     `json:"station_id"`
	StationName        string     `json:"station_name"`
	ScheduledArrival   *time.Time `json:"scheduled_arrival"`
	ScheduledDeparture *time.Time `json:"scheduled_departure"`
	ActualArrival      *time.Time `json:"actual_arrival"`
	ActualDeparture    *time.Time `json:"actual_departure"`
	ArrivalDelay       *int64     `json:"arrival_delay"`
	DepartureDelay     *int64     `json:"departure_delay"`
	Platform           *string    `json:"platform"`
}

func (q *Queries) CreateJourneyStop(ctx context.Context, arg CreateJourneyStopParams) error {
	_, err := q.db.ExecContext(ctx, createJourneyStop,
		arg.ID,
		arg.JourneyID,
		arg.StationID,
		arg.StationName,
		arg.ScheduledArrival,
		arg.ScheduledDeparture,
		arg.ActualArrival,
		arg.ActualDeparture,
		arg.ArrivalDelay,
		arg.DepartureDelay,
		arg.Platform,
	)
	return err
}

const deleteJourney = `-- name: DeleteJourney :exec
DELETE FROM journey WHERE id = ?
`

func (q *Queries) DeleteJourney(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJourney, id)
	return err
}

const getJourneyByID = `-- name: GetJourneyByID :one
SELECT id, train_number, origin_id, origin_name, destination_id, destination_name,
    scheduled_departure, actual_departure, delay, recorded_at
FROM journey WHERE id = ?
`

func (q *Queries) GetJourneyByID(ctx context.Context, id string) (Journey, error) {
	row := q.db.QueryRowContext(ctx, getJourneyByID, id)
	var i Journey
	err := row.Scan(
		&i.ID,
		&i.TrainNumber,
		&i.OriginID,
		&i.OriginName,
		&i.DestinationID,
		&i.DestinationName,
		&i.ScheduledDeparture,
		&i.ActualDeparture,
		&i.Delay,
		&i.RecordedAt,
	)
	return i, err
}

const getJourneyStops = `-- name: GetJourneyStops :many
SELECT id, journey_id, station_id, station_name, scheduled_arrival, scheduled_departure,
    actual_arrival, actual_departure, arrival_delay, departure_delay, platform
FROM journey_stop WHERE journey_id = ? ORDER BY scheduled_departure
`

func (q *Queries) GetJourneyStops(ctx context.Context, journeyID string) ([]JourneyStop, error) {
	rows, err := q.db.QueryContext(ctx, getJourneyStops, journeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JourneyStop{}
	for rows.Next() {
		var i JourneyStop
		if err := rows.Scan(
			&i.ID,
			&i.JourneyID,
			&i.StationID,
			&i.StationName,
			&i.ScheduledArrival,
			&i.ScheduledDeparture,
			&i.ActualArrival,
			&i.ActualDeparture,
			&i.ArrivalDelay,
			&i.DepartureDelay,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJourneys = `-- name: ListJourneys :many
SELECT id, train_number, origin_id, origin_name, destination_id, destination_name,
    scheduled_departure, actual_departure, delay, recorded_at
FROM journey ORDER BY recorded_at DESC LIMIT 100
`

func (q *Queries) ListJourneys(ctx context.Context) ([]Journey, error) {
	rows, err := q.db.QueryContext(ctx, listJourneys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journey{}
	for rows.Next() {
		var i Journey
		if err := rows.Scan(
			&i.ID,
			&i.TrainNumber,
			&i.OriginID,
			&i.OriginName,
			&i.DestinationID,
			&i.DestinationName,
			&i.ScheduledDeparture,
			&i.ActualDeparture,
			&i.Delay,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJourneysByDateRange = `-- name: ListJourneysByDateRange :many
SELECT id, train_number, origin_id, origin_name, destination_id, destination_name,
    scheduled_departure, actual_departure, delay, recorded_at
FROM journey WHERE recorded_at BETWEEN ? AND ? ORDER BY recorded_at DESC
`

type ListJourneysByDateRangeParams struct {
	FromRecordedAt time.Time `json:"from_recorded_at"`
	ToRecordedAt   time.Time `json:"to_recorded_at"`
}

func (q *Queries) ListJourneysByDateRange(ctx context.Context, arg ListJourneysByDateRangeParams) ([]Journey, error) {
	rows, err := q.db.QueryContext(ctx, listJourneysByDateRange, arg.FromRecordedAt, arg.ToRecordedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journey{}
	for rows.Next() {
		var i Journey
		if err := rows.Scan(
			&i.ID,
			&i.TrainNumber,
			&i.OriginID,
			&i.OriginName,
			&i.DestinationID,
			&i.DestinationName,
			&i.ScheduledDeparture,
			&i.ActualDeparture,
			&i.Delay,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJourneysByTrain = `-- name: ListJourneysByTrain :many
SELECT id, train_number, origin_id, origin_name, destination_id, destination_name,
    scheduled_departure, actual_departure, delay, recorded_at
FROM journey WHERE train_number = ? ORDER BY recorded_at DESC
`

func (q *Queries) ListJourneysByTrain(ctx context.Context, trainNumber int64) ([]Journey, error) {
	rows, err := q.db.QueryContext(ctx, listJourneysByTrain, trainNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journey{}
	for rows.Next() {
		var i Journey
		if err := rows.Scan(
			&i.ID,
			&i.TrainNumber,
			&i.OriginID,
			&i.OriginName,
			&i.DestinationID,
			&i.DestinationName,
			&i.ScheduledDeparture,
			&i.ActualDeparture,
			&i.Delay,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJourney = `-- name: UpdateJourney :exec
UPDATE journey SET train_number = ?, origin_id = ?, origin_name = ?, destination_id = ?,
    destination_name = ?, scheduled_departure = ?, actual_departure = ?, delay = ?
WHERE id = ?
`

type UpdateJourneyParams struct {
	TrainNumber        int64      `json:"train_number"`
	OriginID           string     `json:"origin_id"`
	OriginName         string     `json:"origin_name"`
	DestinationID      string     `json:"destination_id"`
	DestinationName    string     `json:"destination_name"`
	ScheduledDeparture *time.Time `json:"scheduled_departure"`
	ActualDeparture    *time.Time `json:"actual_departure"`
	Delay              *int64     `json:"delay"`
	ID                 string     `json:"id"`
}

func (q *Queries) UpdateJourney(ctx context.Context, arg UpdateJourneyParams) error {
	_, err := q.db.ExecContext(ctx, updateJourney,
		arg.TrainNumber,
		arg.OriginID,
		arg.OriginName,
		arg.DestinationID,
		arg.DestinationName,
		arg.ScheduledDeparture,
		arg.ActualDeparture,
		arg.Delay,
		arg.ID,
	)
	return err
}
