// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type DelayVariation struct {
	ID            string    `json:"id"`
	ObservationID string    `json:"observation_id"`
	RecordedAt    time.Time `json:"recorded_at"`
	Delay         int64     `json:"delay"`
}

type ImportMetadatum struct {
	EntityType       string    `json:"entity_type"`
	LastImport       time.Time `json:"last_import"`
	RecordCount      *int64    `json:"record_count"`
	ImportDurationMs *int64    `json:"import_duration_ms"`
	Status           *string   `json:"status"`
	ErrorMessage     *string   `json:"error_message"`
}

type Preferitum struct {
	StationID string `json:"station_id"`
	Name      string `json:"name"`
}

type Station struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Region     *int64     `json:"region"`
	Latitude   *float64   `json:"latitude"`
	Longitude  *float64   `json:"longitude"`
	IsFavorite *int64     `json:"is_favorite"`
	UpdatedAt  *time.Time `json:"updated_at"`
}

type TrainObservation struct {
	ID               string     `json:"id"`
	ObservedAt       time.Time  `json:"observed_at"`
	StationID        string     `json:"station_id"`
	StationName      string     `json:"station_name"`
	ObservationType  string     `json:"observation_type"`
	TrainNumber      int64      `json:"train_number"`
	TrainCategory    *string    `json:"train_category"`
	OriginID         *string    `json:"origin_id"`
	OriginName       *string    `json:"origin_name"`
	DestinationID    *string    `json:"destination_id"`
	DestinationName  *string    `json:"destination_name"`
	ScheduledTime    *time.Time `json:"scheduled_time"`
	Delay            *int64     `json:"delay"`
	Platform         *string    `json:"platform"`
	CirculationState *int64     `json:"circulation_state"`
	ScheduledDate    *string    `json:"scheduled_date"`
	VoyageStopID     *string    `json:"voyage_stop_id"`
}

type Voyage struct {
	ID                 string    `json:"id"`
	TrainNumber        int64     `json:"train_number"`
	TrainCategory      *string   `json:"train_category"`
	OriginID           string    `json:"origin_id"`
	OriginName         string    `json:"origin_name"`
	DestinationID      string    `json:"destination_id"`
	DestinationName    string    `json:"destination_name"`
	ScheduledDate      string    `json:"scheduled_date"`
	ScheduledDeparture time.Time `json:"scheduled_departure"`
	CirculationState   *int64    `json:"circulation_state"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type VoyageStop struct {
	ID                 string     `json:"id"`
	VoyageID           string     `json:"voyage_id"`
	StationID          string     `json:"station_id"`
	StationName        string     `json:"station_name"`
	StopSequence       int64      `json:"stop_sequence"`
	StopType           *string    `json:"stop_type"`
	ScheduledArrival   *time.Time `json:"scheduled_arrival"`
	ScheduledDeparture *time.Time `json:"scheduled_departure"`
	ActualArrival      *time.Time `json:"actual_arrival"`
	ActualDeparture    *time.Time `json:"actual_departure"`
	ArrivalDelay       *int64     `json:"arrival_delay"`
	DepartureDelay     *int64     `json:"departure_delay"`
	Platform           *string    `json:"platform"`
	IsSuppressed       *int64     `json:"is_suppressed"`
	LastObservationAt  *time.Time `json:"last_observation_at"`
}
