// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type DelayVariation struct {
	ID            string    `json:"id"`
	ObservationID string    `json:"observation_id"`
	RecordedAt    time.Time `json:"recorded_at"`
	Delay         int64     `json:"delay"`
}

type ImportMetadatum struct {
	EntityType       string    `json:"entity_type"`
	LastImport       time.Time `json:"last_import"`
	RecordCount      *int64    `json:"record_count"`
	ImportDurationMs *int64    `json:"import_duration_ms"`
	Status           *string   `json:"status"`
	ErrorMessage     *string   `json:"error_message"`
}

type Journey struct {
	ID                 string     `json:"id"`
	TrainNumber        int64      `json:"train_number"`
	OriginID           string     `json:"origin_id"`
	OriginName         string     `json:"origin_name"`
	DestinationID      string     `json:"destination_id"`
	DestinationName    string     `json:"destination_name"`
	ScheduledDeparture *time.Time `json:"scheduled_departure"`
	ActualDeparture    *time.Time `json:"actual_departure"`
	Delay              *int64     `json:"delay"`
	RecordedAt         time.Time  `json:"recorded_at"`
}

type JourneyStop struct {
	ID                 string     `json:"id"`
	JourneyID          string     `json:"journey_id"`
	StationID          string     `json:"station_id"`
	StationName        string     `json:"station_name"`
	ScheduledArrival   *time.Time `json:"scheduled_arrival"`
	ScheduledDeparture *time.Time `json:"scheduled_departure"`
	ActualArrival      *time.Time `json:"actual_arrival"`
	ActualDeparture    *time.Time `json:"actual_departure"`
	ArrivalDelay       *int64     `json:"arrival_delay"`
	DepartureDelay     *int64     `json:"departure_delay"`
	Platform           *string    `json:"platform"`
}

type Preferitum struct {
	StationID string `json:"station_id"`
	Name      string `json:"name"`
}

type Station struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Region     *int64     `json:"region"`
	Latitude   *float64   `json:"latitude"`
	Longitude  *float64   `json:"longitude"`
	IsFavorite *int64     `json:"is_favorite"`
	UpdatedAt  *time.Time `json:"updated_at"`
}

type TrainCheck struct {
	ID          string    `json:"id"`
	WatchedID   string    `json:"watched_id"`
	TrainNumber int64     `json:"train_number"`
	Delay       *int64    `json:"delay"`
	Status      string    `json:"status"`
	CheckedAt   time.Time `json:"checked_at"`
}

type TrainObservation struct {
	ID               string     `json:"id"`
	ObservedAt       time.Time  `json:"observed_at"`
	StationID        string     `json:"station_id"`
	StationName      string     `json:"station_name"`
	ObservationType  string     `json:"observation_type"`
	TrainNumber      int64      `json:"train_number"`
	TrainCategory    *string    `json:"train_category"`
	OriginID         *string    `json:"origin_id"`
	OriginName       *string    `json:"origin_name"`
	DestinationID    *string    `json:"destination_id"`
	DestinationName  *string    `json:"destination_name"`
	ScheduledTime    *time.Time `json:"scheduled_time"`
	Delay            *int64     `json:"delay"`
	Platform         *string    `json:"platform"`
	CirculationState *int64     `json:"circulation_state"`
	ScheduledDate    *string    `json:"scheduled_date"`
}

type WatchedTrain struct {
	ID          string    `json:"id"`
	TrainNumber int64     `json:"train_number"`
	OriginID    string    `json:"origin_id"`
	OriginName  string    `json:"origin_name"`
	Destination string    `json:"destination"`
	DaysOfWeek  *string   `json:"days_of_week"`
	Notes       *string   `json:"notes"`
	Active      *int64    `json:"active"`
	CreatedAt   time.Time `json:"created_at"`
}
