// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferita.sql

package sqlc

import (
	"context"
)

const addPreferita = `-- name: AddPreferita :exec
INSERT OR REPLACE INTO preferita (station_id, name) VALUES (?, ?)
`

type AddPreferitaParams struct {
	StationID string `json:"station_id"`
	Name      string `json:"name"`
}

func (q *Queries) AddPreferita(ctx context.Context, arg AddPreferitaParams) error {
	_, err := q.db.ExecContext(ctx, addPreferita, arg.StationID, arg.Name)
	return err
}

const listPreferite = `-- name: ListPreferite :many
SELECT station_id, name FROM preferita ORDER BY name
`

func (q *Queries) ListPreferite(ctx context.Context) ([]Preferitum, error) {
	rows, err := q.db.QueryContext(ctx, listPreferite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preferitum{}
	for rows.Next() {
		var i Preferitum
		if err := rows.Scan(&i.StationID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const preferitaExists = `-- name: PreferitaExists :one
SELECT COUNT(*) FROM preferita WHERE station_id = ?
`

func (q *Queries) PreferitaExists(ctx context.Context, stationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, preferitaExists, stationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const removePreferita = `-- name: RemovePreferita :exec
DELETE FROM preferita WHERE station_id = ?
`

func (q *Queries) RemovePreferita(ctx context.Context, stationID string) error {
	_, err := q.db.ExecContext(ctx, removePreferita, stationID)
	return err
}
