// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlist.sql

package sqlc

import (
	"context"
	"time"
)

const createTrainCheck = `-- name: CreateTrainCheck :exec
INSERT INTO train_check (id, watched_id, train_number, delay, status, checked_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTrainCheckParams struct {
	ID          string    `json:"id"`
	WatchedID   string    `json:"watched_id"`
	TrainNumber int64     `json:"train_number"`
	Delay       *int64    `json:"delay"`
	Status      string    `json:"status"`
	CheckedAt   time.Time `json:"checked_at"`
}

func (q *Queries) CreateTrainCheck(ctx context.Context, arg CreateTrainCheckParams) error {
	_, err := q.db.ExecContext(ctx, createTrainCheck,
		arg.ID,
		arg.WatchedID,
		arg.TrainNumber,
		arg.Delay,
		arg.Status,
		arg.CheckedAt,
	)
	return err
}

const createWatchedTrain = `-- name: CreateWatchedTrain :exec
INSERT INTO watched_train (id, train_number, origin_id, origin_name, destination, days_of_week, notes, active, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWatchedTrainParams struct {
	ID          string    `json:"id"`
	TrainNumber int64     `json:"train_number"`
	OriginID    string    `json:"origin_id"`
	OriginName  string    `json:"origin_name"`
	Destination string    `json:"destination"`
	DaysOfWeek  *string   `json:"days_of_week"`
	Notes       *string   `json:"notes"`
	Active      *int64    `json:"active"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateWatchedTrain(ctx context.Context, arg CreateWatchedTrainParams) error {
	_, err := q.db.ExecContext(ctx, createWatchedTrain,
		arg.ID,
		arg.TrainNumber,
		arg.OriginID,
		arg.OriginName,
		arg.Destination,
		arg.DaysOfWeek,
		arg.Notes,
		arg.Active,
		arg.CreatedAt,
	)
	return err
}

const deleteWatchedTrain = `-- name: DeleteWatchedTrain :exec
DELETE FROM watched_train WHERE id = ?
`

func (q *Queries) DeleteWatchedTrain(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWatchedTrain, id)
	return err
}

const getRecentTrainChecks = `-- name: GetRecentTrainChecks :many
SELECT id, watched_id, train_number, delay, status, checked_at
FROM train_check ORDER BY checked_at DESC LIMIT ?
`

func (q *Queries) GetRecentTrainChecks(ctx context.Context, limit int64) ([]TrainCheck, error) {
	rows, err := q.db.QueryContext(ctx, getRecentTrainChecks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainCheck{}
	for rows.Next() {
		var i TrainCheck
		if err := rows.Scan(
			&i.ID,
			&i.WatchedID,
			&i.TrainNumber,
			&i.Delay,
			&i.Status,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainChecksByWatched = `-- name: GetTrainChecksByWatched :many
SELECT id, watched_id, train_number, delay, status, checked_at
FROM train_check WHERE watched_id = ? ORDER BY checked_at DESC LIMIT 100
`

func (q *Queries) GetTrainChecksByWatched(ctx context.Context, watchedID string) ([]TrainCheck, error) {
	rows, err := q.db.QueryContext(ctx, getTrainChecksByWatched, watchedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainCheck{}
	for rows.Next() {
		var i TrainCheck
		if err := rows.Scan(
			&i.ID,
			&i.WatchedID,
			&i.TrainNumber,
			&i.Delay,
			&i.Status,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchedTrainByID = `-- name: GetWatchedTrainByID :one
SELECT id, train_number, origin_id, origin_name, destination, days_of_week, notes, active, created_at
FROM watched_train WHERE id = ?
`

func (q *Queries) GetWatchedTrainByID(ctx context.Context, id string) (WatchedTrain, error) {
	row := q.db.QueryRowContext(ctx, getWatchedTrainByID, id)
	var i WatchedTrain
	err := row.Scan(
		&i.ID,
		&i.TrainNumber,
		&i.OriginID,
		&i.OriginName,
		&i.Destination,
		&i.DaysOfWeek,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveWatchedTrains = `-- name: ListActiveWatchedTrains :many
SELECT id, train_number, origin_id, origin_name, destination, days_of_week, notes, active, created_at
FROM watched_train WHERE active = 1 ORDER BY created_at DESC
`

func (q *Queries) ListActiveWatchedTrains(ctx context.Context) ([]WatchedTrain, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWatchedTrains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchedTrain{}
	for rows.Next() {
		var i WatchedTrain
		if err := rows.Scan(
			&i.ID,
			&i.TrainNumber,
			&i.OriginID,
			&i.OriginName,
			&i.Destination,
			&i.DaysOfWeek,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchedTrains = `-- name: ListWatchedTrains :many
SELECT id, train_number, origin_id, origin_name, destination, days_of_week, notes, active, created_at
FROM watched_train ORDER BY created_at DESC
`

func (q *Queries) ListWatchedTrains(ctx context.Context) ([]WatchedTrain, error) {
	rows, err := q.db.QueryContext(ctx, listWatchedTrains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchedTrain{}
	for rows.Next() {
		var i WatchedTrain
		if err := rows.Scan(
			&i.ID,
			&i.TrainNumber,
			&i.OriginID,
			&i.OriginName,
			&i.Destination,
			&i.DaysOfWeek,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWatchedTrain = `-- name: UpdateWatchedTrain :exec
UPDATE watched_train SET train_number = ?, origin_id = ?, origin_name = ?, destination = ?,
    days_of_week = ?, notes = ?, active = ? WHERE id = ?
`

type UpdateWatchedTrainParams struct {
	TrainNumber int64   `json:"train_number"`
	OriginID    string  `json:"origin_id"`
	OriginName  string  `json:"origin_name"`
	Destination string  `json:"destination"`
	DaysOfWeek  *string `json:"days_of_week"`
	Notes       *string `json:"notes"`
	Active      *int64  `json:"active"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateWatchedTrain(ctx context.Context, arg UpdateWatchedTrainParams) error {
	_, err := q.db.ExecContext(ctx, updateWatchedTrain,
		arg.TrainNumber,
		arg.OriginID,
		arg.OriginName,
		arg.Destination,
		arg.DaysOfWeek,
		arg.Notes,
		arg.Active,
		arg.ID,
	)
	return err
}
